### PR TITLE
Replaced all logo jpgs with transparent pngs except for spotlight.

### PR DESCRIPTION
**Pull request by akashsara**
Didn't touch existing .pngs(already transparent), the images in gallery and other background which don't need to be in .png. 

All the logos are now transparent jpgs. 

Only spotlight.jpg is difficult to convert. If you have a better quality version of it, I can convert it.

### CODE REVIEW

**Comment by Pratul1997** [comment]
@akashsara ,
There are some conflicts in the merge,
Kindly keep your forks in sync.
I will be more than happy to merge when conflicts are resolved.

**Comment by akashsara** [comment]
@Pratul1997 done

**Comment by Pratul1997** [comment]
@akashsara Thanks for responding,
Now half of the images are in JPEG format, kindly convert all to PNG form 
and take corresponding changes in Index.html file too.

**Comment by akashsara** [comment]
@Pratul1997 
I'm not really sure what changes were made to the JPEG images as there were no changes(It said no conflicts at the time) when I submitted the original PR. All the images are ready in PNG form and have been changed in index.html as well already.

I'm guessing that the conflict was because I'd removed the JPEG files after converting them to PNG files.

**Comment by Pratul1997** [comment]
@akashsara 
Basically, there were 5 PR, when I woke up today, And yours was the 3rd PR.
When I merged the first two, my branch was 2 commit ahead of your branch,
And there was a conflict between my current status of the branch and your branch.
Therefore you need to keep your fork in sync.
After you have synced the make the necessary changes(changes you made in the first commit) and then commit and next PR.
Hope things are clear, if you have any doubt then let me know.

**Comment by akashsara** [comment]
@Pratul1997 
That clears things up. 

I checked out the commit that modified the image. It did some lossless optimization of the images. Now the problem is, if I modify the images to add transparency and convert to a PNG, I'm pretty sure that optimization will be lost. So they'll have to rerun the optimization on all the images. What do you suggest we do?

**Comment by Pratul1997** [comment]
@akashsara Thanks for responding,
So in your first commit where all image qualities decreased?

**Comment by Pratul1997** [comment]
@akashsara In your first commit things were good, bring the conditions like the first commit.
Images and their path.

**Comment by akashsara** [comment]
@Pratul1997 
Done! 
To clarify, the quality of all the images are the same. The only difference is that in my first commit all the images are transparent PNGs with a larger filesize(unoptimized) whereas in the other commit, the images are non-transparent JPEGs with a smaller filesize(optimized).

**Comment by Pratul1997** [comment]
@akashsara 
Thanks for great efforts!!
We would be pleased to see more contribution from you.
Remember To keep the forks in Sync.

**Pull request merged**
